### ISSUE TITLE
yolov8-pose tritonserver infer

### ISSUE THREAD

**Issue by minjea1588** [YunghuiHsu/deepstream-yolo-pose#5]
hello! Thank you for making a good source.

I am running yolov8-pose with tritonserver and running 
`pose_src_pad_buffer_probe` function, and I confirmed that an error occurs in this part
`out[..., :4] = map_to_zero_one(out[..., :4])`. Is there any solution?

**Comment by YunghuiHsu** [comment]
Hi minjea1588:

I'm gonna need more information from you to debug this.

**Comment by minjea1588** [comment]
ubuntu18.04
triton docker : nvcr.io/nvidia/tritonserver:21.10-py3
deepstream docker : nvcr.io/nvidia/deepstream:6.0-triton

triton config.pbtxt
[config.txt](https://github.com/YunghuiHsu/deepstream-yolo-pose/files/1

deepstream config
[dstest_yolo_nopostprocess_v8_pose_triton.txt](https://github.com/YunghuiHsu/deepstream-yolo-pose/files/12509972/dstest_yolo_nopostprocess_v8_pose_triton.txt)
2509962/config.txt)

deepstream_yolov8_pose_triton.py
`import sys
import io
sys.path.append("../")
import gi
gi.require_version("Gst", "1.0")
from gi.repository import GObject, Gst
from common.is_aarch_64 import is_aarch64
from common.bus_call import bus_call
from yolo_parser import nvds_infer_parse_custom_yolo, DetectionParam, NmsParam, BoxSizeParam
import pyds
import ctypes
import numpy as np
import cv2
from utils.utils import map_to_zero_one, postprocess
from utils.display import dispaly_frame_pose, add_obj_meta
from utils.FPS import PERF_DATA
import time

perf_data = None
MUXER_OUTPUT_WIDTH = 640  # stream input
MUXER_OUTPUT_HEIGHT = 640  # stream input
CLASS_NB = 80
ACCURACY_ALL_CLASS = 0.5
UNTRACKED_OBJECT_ID = 0xffffffffffffffff
IMAGE_HEIGHT = 640
IMAGE_WIDTH = 640
MIN_BOX_WIDTH = 32
MIN_BOX_HEIGHT = 32
TOP_K = 20
IOU_THRESHOLD = 0.3
MODEL_CONFIG = 'dstest_yolo_nopostprocess_v8_pose_triton.txt'
OUTPUT_VIDEO_NAME = "./out.mp4"
conf_thres = 0.25
iou_thres = 0.35
data_type_map = {pyds.NvDsInferDataType.FLOAT: ctypes.c_float,
                    pyds.NvDsInferDataType.INT8: ctypes.c_int8,
                    pyds.NvDsInferDataType.INT32: ctypes.c_int32}


def get_label_names_from_file(filepath):
    """ Read a label file and convert it to string list """
    f = io.open(filepath, "r")
    labels = f.readlines()
    labels = [elm[:-1] for elm in labels]
    f.close()
    return labels


def make_elm_or_print_err(factoryname, name, printedname, detail=""):
    """ Creates an element with Gst Element Factory make.
        Return the element  if successfully created, otherwise print
        to stderr and return None.
    """
    print("Creating", printedname)
    elm = Gst.ElementFactory.make(factoryname, name)
    if not elm:
        sys.stderr.write("Unable to create " + printedname + " \n")
        if detail:
            sys.stderr.write(detail)
    return elm


def osd_sink_pad_buffer_probe(pad, info, u_data):
    # Intiallizing object counter with 0.
    obj_counter = dict(enumerate([0] * CLASS_NB))
    num_rects = 0

    gst_buffer = info.get_buffer()
    if not gst_buffer:
        print("Unable to get GstBuffer ")
        return

    # Retrieve batch metadata from the gst_buffer
    # Note that pyds.gst_buffer_get_nvds_batch_meta() expects the
    # C address of gst_buffer as input, which is obtained with hash(gst_buffer)
    batch_meta = pyds.gst_buffer_get_nvds_batch_meta(hash(gst_buffer))
    l_frame = batch_meta.frame_meta_list
    while l_frame is not None:
        try:
            # Note that l_frame.data needs a cast to pyds.NvDsFrameMeta
            # The casting also keeps ownership of the underlying memory
            # in the C code, so the Python garbage collector will leave
            # it alone.
            frame_meta = pyds.NvDsFrameMeta.cast(l_frame.data)
        except StopIteration:
            break

        # frame_number = frame_meta.frame_num
        num_rects = frame_meta.num_obj_meta
        frame_number = frame_meta.frame_num
        l_obj = frame_meta.obj_meta_list
        while l_obj is not None:
            try:
                # Casting l_obj.data to pyds.NvDsObjectMeta
                obj_meta = pyds.NvDsObjectMeta.cast(l_obj.data)
            except StopIteration:
                break
            # obj_counter[obj_meta.class_id] += 1
            try:
                l_obj = l_obj.next
            except StopIteration:
                break

        # Acquiring a display meta object. The memory ownership remains in
        # the C code so downstream plugins can still access it. Otherwise
        # the garbage collector will claim it when this probe function exits.
        display_meta = pyds.nvds_acquire_display_meta_from_pool(batch_meta)
        display_meta.num_labels = 1
        py_nvosd_text_params = display_meta.text_params[0]
        # Setting display text to be shown on screen
        # Note that the pyds module allocates a buffer for the string, and the
        # memory will not be claimed by the garbage collector.
        # Reading the display_text field here will return the C address of the
        # allocated string. Use pyds.get_string() to get the string content.
        id_dict = {
            val: index
            for index, val in enumerate(get_label_names_from_file("labels.txt"))
        }
        disp_string = "Frame Number={} Number of Objects={} Vehicle_count={} Person_count={}"
        py_nvosd_text_params.display_text = disp_string.format(
            frame_number,
            num_rects,
            obj_counter[id_dict["car"]],
            obj_counter[id_dict["person"]],
        )

        # Now set the offsets where the string should appear
        py_nvosd_text_params.x_offset = 10
        py_nvosd_text_params.y_offset = 12

        # Font , font-color and font-size
        py_nvosd_text_params.font_params.font_name = "Serif"
        py_nvosd_text_params.font_params.font_size = 10
        # set(red, green, blue, alpha); set to White
        py_nvosd_text_params.font_params.font_color.set(1.0, 1.0, 1.0, 1.0)

        # Text background color
        py_nvosd_text_params.set_bg_clr = 1
        # set(red, green, blue, alpha); set to Black
        py_nvosd_text_params.text_bg_clr.set(0.0, 0.0, 0.0, 1.0)
        # Using pyds.get_string() to get display_text as string
        print(pyds.get_string(py_nvosd_text_params.display_text))
        pyds.nvds_add_display_meta_to_frame(frame_meta, display_meta)
        try:
            l_frame = l_frame.next
        except StopIteration:
            break

    return Gst.PadProbeReturn.OK


def draw_bounding_box(img, info, i):
    # label = f'{CLASSES[class_id]} ({confidence:.2f})'
    label = 'class'
    color = (255,0,255)
    # print(info)
    x = info['box'][0]
    y = info['box'][1]
    x_plus_w = info['box'][0] + info['box'][2]
    y_plus_h = info['box'][1] + info['box'][3]
    cv2.rectangle(img, (x, y), (x_plus_w, y_plus_h), color, 2)
    cv2.putText(img, label, (x - 10, y - 10), cv2.FONT_HERSHEY_DUPLEX, 0.7, color, 1)
    cv2.imwrite(f"frames/result{i}.jpg", img)

def add_obj_meta_to_frame(frame_object, batch_meta, frame_meta, label_names):
    """ Inserts an object into the metadata """
    # this is a good place to insert objects into the metadata.
    # Here's an example of inserting a single object.
    obj_meta = pyds.nvds_acquire_obj_meta_from_pool(batch_meta)
    # Set bbox properties. These are in input resolution.
    rect_params = obj_meta.rect_params
    rect_params.left = int(IMAGE_WIDTH * frame_object.left)
    rect_params.top = int(IMAGE_HEIGHT * frame_object.top)
    rect_params.width = int(IMAGE_WIDTH * frame_object.width)
    rect_params.height = int(IMAGE_HEIGHT * frame_object.height)

    # Semi-transparent yellow backgroud 
    rect_params.has_bg_color = 0
    rect_params.bg_color.set(1, 1, 0, 0.4)

    # Red border of width 3
    rect_params.border_width = 3
    rect_params.border_color.set(1, 0, 0, 1)

    # Set object info including class, detection confidence, etc.
    obj_meta.confidence = frame_object.detectionConfidence
    obj_meta.class_id = frame_object.classId

    # There is no tracking ID upon detection. The tracker will
    # assign an ID.
    obj_meta.object_id = UNTRACKED_OBJECT_ID

    lbl_id = frame_object.classId
    if lbl_id >= len(label_names):
        lbl_id = 0

    # Set the object classification label.
    obj_meta.obj_label = label_names[lbl_id]

    # Set display text for the object.
    txt_params = obj_meta.text_params
    if txt_params.display_text:
        pyds.free_buffer(txt_params.display_text)

    txt_params.x_offset = int(rect_params.left)
    txt_params.y_offset = max(0, int(rect_params.top) - 10)
    txt_params.display_text = (
        label_names[lbl_id] + " " + "{:04.3f}".format(frame_object.detectionConfidence)
    )
    # Font , font-color and font-size
    txt_params.font_params.font_name = "Serif"
    txt_params.font_params.font_size = 10
    # set(red, green, blue, alpha); set to White
    txt_params.font_params.font_color.set(1.0, 1.0, 1.0, 1.0)

    # Text background color
    txt_params.set_bg_clr = 1
    # set(red, green, blue, alpha); set to Black
    txt_params.text_bg_clr.set(0.0, 0.0, 0.0, 1.0)

    # Inser the object into current frame meta
    # This object has no parent
    pyds.nvds_add_obj_meta_to_frame(frame_meta, obj_meta, None)


def pose_src_pad_buffer_probe(pad, info, u_data):
    t = time.time()

    frame_number = 0
    num_rects = 0

    gst_buffer = info.get_buffer()
    if not gst_buffer:
        print("Unable to get GstBuffer ")
        return

    batch_meta = pyds.gst_buffer_get_nvds_batch_meta(hash(gst_buffer))

    l_frame = batch_meta.frame_meta_list
    while l_frame is not None:
        try:
            frame_meta = pyds.NvDsFrameMeta.cast(l_frame.data)
        except StopIteration:
            break

        frame_number = frame_meta.frame_num
        num_rects = frame_meta.num_obj_meta
        pad_index = frame_meta.pad_index
        l_usr = frame_meta.frame_user_meta_list

        while l_usr is not None:
            try:
                # Casting l_obj.data to pyds.NvDsUserMeta
                user_meta = pyds.NvDsUserMeta.cast(l_usr.data)
            except StopIteration:
                break

            # get tensor output
            if (user_meta.base_meta.meta_type !=
                    pyds.NvDsMetaType.NVDSINFER_TENSOR_OUTPUT_META):  # NVDSINFER_TENSOR_OUTPUT_META
                try:
                    l_usr = l_usr.next
                except StopIteration:
                    break
                continue

            try:
                tensor_meta = pyds.NvDsInferTensorMeta.cast(
                    user_meta.user_meta_data)

                assert tensor_meta.num_output_layers == 1, f'Check number of model output layer : {tensor_meta.num_output_layers}'
                # layer_output_info = layers_info[0]
                layer_output_info = pyds.get_nvds_LayerInfo(tensor_meta, 0)  # as num_output_layers == 1

                network_info = tensor_meta.network_info
                input_shape = (network_info.width, network_info.height)
                
                if frame_number == 0 :
                    print(f'\tmodel input_shape  : {input_shape}')


                # remove zeros from both ends of the array. 'b' : 'both'
                dims = np.trim_zeros(layer_output_info.inferDims.d, 'b')
                
                if frame_number == 0 :
                    print(f'\tModel output dimension from LayerInfo: {dims}')

                    output_message = f'\tCheck model output shape: {layer_output_info.inferDims.numElements}, '
                    output_message += f'given OUT_SHAPE : {dims}'
                    assert layer_output_info.inferDims.numElements == np.prod(dims), output_message
                    
                
                # load float* buffer to python
                cdata_type = data_type_map[layer_output_info.dataType]
                ptr = ctypes.cast(pyds.get_ptr(layer_output_info.buffer), 
                                  ctypes.POINTER(cdata_type))
                # Determine the size of the array
                out = np.ctypeslib.as_array(ptr, shape=dims)

                if frame_number == 0 :
                    print(f'\tLoad Model Output From LayerInfo. Output Shape : {out.shape}')
                # [Optional] Postprocess for YOLOv7-pose(with YoloLayer_TRT_v7.0 Layer) prediction tensor
                # (https://github.com/nanmi/yolov7-pose/)
                # (57001, 1, 1) > (57000, 1, 1) > (1000, 57)
                # out = out[1:, ...].reshape(-1 , 57)   # or out.squeeze()[1:].reshape(-1 , 57)
                # ----------------------------------------------------------------------------------------------------------------------

                #  Explicitly specify batch dimensions
                if np.ndim(out) < 3:
                    out = out[np.newaxis, :]
                    # print(f'add axis 0 for model output : {out.shape}')

                # [Optional] Postprocess for yolov8-pose prediction tensor
                # (https://github.com/triple-Mu/YOLOv8-TensorRT/tree/triplemu/pose-infer)
                # 　(batch, 56, 8400)　＞(batch, 8400, 56) for yolov8
                out = out.transpose((0, 2, 1))

                # out = map_to_zero_one_copy(out)
                # make pseudo class prob
                cls_prob = np.ones((out.shape[0], out.shape[1], 1), dtype=np.uint8)
                out[..., :4] = map_to_zero_one(out[..., :4])  # scalar prob to [0, 1]
                # insert pseudo class prob into predictions
                out = np.concatenate((out[..., :5], cls_prob, out[..., 5:]), axis=-1)
                out[..., [0, 2]] = out[..., [0, 2]] * network_info.width  # scale to screen width
                out[..., [1, 3]] = out[..., [1, 3]] * network_info.height  # scale to screen height
                # ----------------------------------------------------------------------------------------------------------------------

                output_shape = (MUXER_OUTPUT_HEIGHT, MUXER_OUTPUT_WIDTH)
                if frame_number == 0 :
                    print(f'\tModel output : {out.shape}, The coordinates of the keypoint are rescaled to (h, w) : {output_shape}')
                print("out : ", out.shape)
                pred = postprocess(out, output_shape, input_shape,
                                   conf_thres=conf_thres, iou_thres=iou_thres)
                boxes, confs, kpts = pred
                # print("boxex, confs ", boxes, confs)
                if len(boxes) > 0 and len(confs) > 0 and len(kpts) > 0:
                    add_obj_meta(frame_meta, batch_meta, boxes[0], confs[0])
                    dispaly_frame_pose(frame_meta, batch_meta,
                                       boxes[0], confs[0], kpts[0])

            except StopIteration:
                break

            try:
                l_usr = l_usr.next
            except StopIteration:
                break


        # update frame rate through this probe
        stream_index = "stream{0}".format(frame_meta.pad_index)
        global perf_data
        perf_data.update_fps(stream_index)

        try:
            # indicate inference is performed on the frame
            frame_meta.bInferDone = True
            l_frame = l_frame.next
        except StopIteration:
            break
        # pyds.nvds_acquire_meta_lock(batch_meta)
        # frame_meta.bInferDone = True
        # pyds.nvds_release_meta_lock(batch_meta)

    return Gst.PadProbeReturn.OK


def main(args):
    global perf_data
    # Check input arguments
    if len(args) != 2:
        sys.stderr.write("usage: %s <media file or uri>\n" % args[0])
        sys.exit(1)

    number_sources = len(args) - 1
    perf_data = PERF_DATA(number_sources)
    # Standard GStreamer initialization
    GObject.threads_init()
    Gst.init(None)

    # Create gstreamer elements
    # Create Pipeline element that will form a connection of other elements
    print("Creating Pipeline \n ")
    pipeline = Gst.Pipeline()

    if not pipeline:
        sys.stderr.write(" Unable to create Pipeline \n")

    # Source element for reading from the file
    source = make_elm_or_print_err("filesrc", "file-source", "Source")

    # Since the data format in the input file is elementary h264 stream,
    # we need a h264parser
    h264parser = make_elm_or_print_err("h264parse", "h264-parser", "H264Parser")

    # Use nvdec_h264 for hardware accelerated decode on GPU
    decoder = make_elm_or_print_err("nvv4l2decoder", "nvv4l2-decoder", "Decoder")

    # Create nvstreammux instance to form batches from one or more sources.
    streammux = make_elm_or_print_err("nvstreammux", "Stream-muxer", "NvStreamMux")

    # Use nvinferserver to run inferencing on decoder's output,
    # behaviour of inferencing is set through config file
    pgie = make_elm_or_print_err("nvinferserver", "primary-inference", "Nvinferserver")

    # Use convertor to convert from NV12 to RGBA as required by nvosd
    nvvidconv = make_elm_or_print_err("nvvideoconvert", "convertor", "Nvvidconv")

    # Create OSD to draw on the converted RGBA buffer
    nvosd = make_elm_or_print_err("nvdsosd", "onscreendisplay", "OSD (nvosd)")


    # Finally encode and save the osd output
    queue = make_elm_or_print_err("queue", "queue", "Queue")

    nvvidconv2 = make_elm_or_print_err("nvvideoconvert", "convertor2", "Converter 2 (nvvidconv2)")

    capsfilter = make_elm_or_print_err("capsfilter", "capsfilter", "capsfilter")

    caps = Gst.Caps.from_string("video/x-raw, format=I420")
    capsfilter.set_property("caps", caps)

    # On Jetson, there is a problem with the encoder failing to initialize
    # due to limitation on TLS usage. To work around this, preload libgomp.
    # Add a reminder here in case the user forgets.
    preload_reminder = "If the following error is encountered:\n" + \
                       "/usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block\n" + \
                       "Preload the offending library:\n" + \
                       "export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1\n"
    encoder = make_elm_or_print_err("avenc_mpeg4", "encoder", "Encoder", preload_reminder)

    encoder.set_property("bitrate", 2000000)

    codeparser = make_elm_or_print_err("mpeg4videoparse", "mpeg4-parser", 'Code Parser')

    container = make_elm_or_print_err("qtmux", "qtmux", "Container")

    sink = make_elm_or_print_err("filesink", "filesink", "Sink")

    sink.set_property("location", OUTPUT_VIDEO_NAME)
    sink.set_property("sync", 0)
    sink.set_property("async", 0)

    print("Playing file %s " % args[1])
    source.set_property("location", args[1])
    streammux.set_property("width", IMAGE_WIDTH)
    streammux.set_property("height", IMAGE_HEIGHT)
    streammux.set_property("batch-size", 1)
    streammux.set_property("batched-push-timeout", 4000000)
    pgie.set_property("config-file-path", MODEL_CONFIG)

    print("Adding elements to Pipeline \n")
    pipeline.add(source)
    pipeline.add(h264parser)
    pipeline.add(decoder)
    pipeline.add(streammux)
    pipeline.add(pgie)
    pipeline.add(nvvidconv)
    pipeline.add(nvosd)
    pipeline.add(queue)
    pipeline.add(nvvidconv2)
    pipeline.add(capsfilter)
    pipeline.add(encoder)
    pipeline.add(codeparser)
    pipeline.add(container)
    pipeline.add(sink)

    # we link the elements together
    # file-source -> h264-parser -> nvh264-decoder ->
    # nvinfer -> nvvidconv -> nvosd -> video-renderer
    print("Linking elements in the Pipeline \n")
    source.link(h264parser)
    h264parser.link(decoder)

    sinkpad = streammux.get_request_pad("sink_0")
    if not sinkpad:
        sys.stderr.write(" Unable to get the sink pad of streammux \n")
    srcpad = decoder.get_static_pad("src")
    if not srcpad:
        sys.stderr.write(" Unable to get source pad of decoder \n")
    srcpad.link(sinkpad)
    streammux.link(pgie)
    pgie.link(nvvidconv)
    nvvidconv.link(nvosd)
    nvosd.link(queue)
    queue.link(nvvidconv2)
    nvvidconv2.link(capsfilter)
    capsfilter.link(encoder)
    encoder.link(codeparser)
    codeparser.link(container)
    container.link(sink)

    # create an event loop and feed gstreamer bus mesages to it
    loop = GObject.MainLoop()
    bus = pipeline.get_bus()
    bus.add_signal_watch()
    bus.connect("message", bus_call, loop)

    # Add a probe on the primary-infer source pad to get inference output tensors
    pgiesrcpad = pgie.get_static_pad("src")
    if not pgiesrcpad:
        sys.stderr.write(" Unable to get src pad of primary infer \n")

    pgiesrcpad.add_probe(Gst.PadProbeType.BUFFER, pose_src_pad_buffer_probe, 0)

    # Lets add probe to get informed of the meta data generated, we add probe to
    # the sink pad of the osd element, since by that time, the buffer would have
    # had got all the metadata.
    osdsinkpad = nvosd.get_static_pad("sink")
    if not osdsinkpad:
        sys.stderr.write(" Unable to get sink pad of nvosd \n")

    osdsinkpad.add_probe(Gst.PadProbeType.BUFFER, osd_sink_pad_buffer_probe, 0)

    # start play back and listen to events
    print("Starting pipeline \n")
    pipeline.set_state(Gst.State.PLAYING)
    try:
        loop.run()
    except:
        pass
    # cleanup
    pipeline.set_state(Gst.State.NULL)


if __name__ == "__main__":
    sys.argv.append("../../../../samples/streams/sample_720p.h264")
    sys.exit(main(sys.argv))`
    
 
![image](https://github.com/YunghuiHsu/deepstream-yolo-pose/assets/104705868/cc5e3608-545a-41b6-9a90-e5430955d5b2)

**Comment by minjea1588** [comment]
ubuntu18.04
triton docker : nvcr.io/nvidia/tritonserver:21.10-py3
deepstream docker : nvcr.io/nvidia/deepstream:6.0-triton

triton config.pbtxt
[config.txt](https://github.com/YunghuiHsu/deepstream-yolo-pose/files/12510019/config.txt)

deepstream config
[dstest_yolo_nopostprocess_v8_pose_triton.txt](https://github.com/YunghuiHsu/deepstream-yolo-pose/files/12510024/dstest_yolo_nopostprocess_v8_pose_triton.txt)

`def pose_src_pad_buffer_probe(pad, info, u_data):
    t = time.time()

    frame_number = 0
    num_rects = 0

    gst_buffer = info.get_buffer()
    if not gst_buffer:
        print("Unable to get GstBuffer ")
        return

    batch_meta = pyds.gst_buffer_get_nvds_batch_meta(hash(gst_buffer))

    l_frame = batch_meta.frame_meta_list
    while l_frame is not None:
        try:
            frame_meta = pyds.NvDsFrameMeta.cast(l_frame.data)
        except StopIteration:
            break

        frame_number = frame_meta.frame_num
        num_rects = frame_meta.num_obj_meta
        pad_index = frame_meta.pad_index
        l_usr = frame_meta.frame_user_meta_list

        while l_usr is not None:
            try:
                # Casting l_obj.data to pyds.NvDsUserMeta
                user_meta = pyds.NvDsUserMeta.cast(l_usr.data)
            except StopIteration:
                break

            # get tensor output
            if (user_meta.base_meta.meta_type !=
                    pyds.NvDsMetaType.NVDSINFER_TENSOR_OUTPUT_META):  # NVDSINFER_TENSOR_OUTPUT_META
                try:
                    l_usr = l_usr.next
                except StopIteration:
                    break
                continue

            try:
                tensor_meta = pyds.NvDsInferTensorMeta.cast(
                    user_meta.user_meta_data)

                assert tensor_meta.num_output_layers == 1, f'Check number of model output layer : {tensor_meta.num_output_layers}'
                # layer_output_info = layers_info[0]
                layer_output_info = pyds.get_nvds_LayerInfo(tensor_meta, 0)  # as num_output_layers == 1

                network_info = tensor_meta.network_info
                input_shape = (network_info.width, network_info.height)
                
                if frame_number == 0 :
                    print(f'\tmodel input_shape  : {input_shape}')


                # remove zeros from both ends of the array. 'b' : 'both'
                dims = np.trim_zeros(layer_output_info.inferDims.d, 'b')
                
                if frame_number == 0 :
                    print(f'\tModel output dimension from LayerInfo: {dims}')

                    output_message = f'\tCheck model output shape: {layer_output_info.inferDims.numElements}, '
                    output_message += f'given OUT_SHAPE : {dims}'
                    assert layer_output_info.inferDims.numElements == np.prod(dims), output_message
                    
                
                # load float* buffer to python
                cdata_type = data_type_map[layer_output_info.dataType]
                ptr = ctypes.cast(pyds.get_ptr(layer_output_info.buffer), 
                                  ctypes.POINTER(cdata_type))
                # Determine the size of the array
                out = np.ctypeslib.as_array(ptr, shape=dims)

                if frame_number == 0 :
                    print(f'\tLoad Model Output From LayerInfo. Output Shape : {out.shape}')
                # [Optional] Postprocess for YOLOv7-pose(with YoloLayer_TRT_v7.0 Layer) prediction tensor
                # (https://github.com/nanmi/yolov7-pose/)
                # (57001, 1, 1) > (57000, 1, 1) > (1000, 57)
                # out = out[1:, ...].reshape(-1 , 57)   # or out.squeeze()[1:].reshape(-1 , 57)
                # ----------------------------------------------------------------------------------------------------------------------

                #  Explicitly specify batch dimensions
                if np.ndim(out) < 3:
                    out = out[np.newaxis, :]
                    # print(f'add axis 0 for model output : {out.shape}')

                # [Optional] Postprocess for yolov8-pose prediction tensor
                # (https://github.com/triple-Mu/YOLOv8-TensorRT/tree/triplemu/pose-infer)
                # 　(batch, 56, 8400)　＞(batch, 8400, 56) for yolov8
                out = out.transpose((0, 2, 1))

                # out = map_to_zero_one_copy(out)
                # make pseudo class prob
                cls_prob = np.ones((out.shape[0], out.shape[1], 1), dtype=np.uint8)
                out[..., :4] = map_to_zero_one(out[..., :4])  # scalar prob to [0, 1]
                # insert pseudo class prob into predictions
                out = np.concatenate((out[..., :5], cls_prob, out[..., 5:]), axis=-1)
                out[..., [0, 2]] = out[..., [0, 2]] * network_info.width  # scale to screen width
                out[..., [1, 3]] = out[..., [1, 3]] * network_info.height  # scale to screen height
                # ----------------------------------------------------------------------------------------------------------------------

                output_shape = (MUXER_OUTPUT_HEIGHT, MUXER_OUTPUT_WIDTH)
                if frame_number == 0 :
                    print(f'\tModel output : {out.shape}, The coordinates of the keypoint are rescaled to (h, w) : {output_shape}')
                print("out : ", out.shape)
                pred = postprocess(out, output_shape, input_shape,
                                   conf_thres=conf_thres, iou_thres=iou_thres)
                boxes, confs, kpts = pred
                # print("boxex, confs ", boxes, confs)
                if len(boxes) > 0 and len(confs) > 0 and len(kpts) > 0:
                    add_obj_meta(frame_meta, batch_meta, boxes[0], confs[0])
                    dispaly_frame_pose(frame_meta, batch_meta,
                                       boxes[0], confs[0], kpts[0])

            except StopIteration:
                break

            try:
                l_usr = l_usr.next
            except StopIteration:
                break


        # update frame rate through this probe
        stream_index = "stream{0}".format(frame_meta.pad_index)
        global perf_data
        perf_data.update_fps(stream_index)

        try:
            # indicate inference is performed on the frame
            frame_meta.bInferDone = True
            l_frame = l_frame.next
        except StopIteration:
            break

    return Gst.PadProbeReturn.OK`
![image](https://github.com/YunghuiHsu/deepstream-yolo-pose/assets/104705868/a4cd89fc-f3c0-419c-9690-0fa8f5c9512a)


When using nvinfer, it works normally, but when using triton server, the error occurs and does not proceed to the next frame.

**Comment by YunghuiHsu** [comment]
I guess something wrong in [dstest_yolo_nopostprocess_v8_pose_triton.txt](https://github.com/YunghuiHsu/deepstream-yolo-pose/files/12510024/dstest_yolo_nopostprocess_v8_pose_triton.txt):

Maybe should not use 'custom_lib'
```
  postprocess {
    labelfile_path: "/opt/nvidia/deepstream/deepstream-6.0/sources/deepstream_python_apps/apps/deepstream-imagedata-multistream/labels.txt"
    other {}
  }
  extra {
    copy_input_to_host_buffers: false
  }

  custom_lib {
    path: "/opt/nvidia/deepstream/deepstream-6.0/sources/libs/nvdsinfer_customparser/libnvds_infercustomparser.so"
  }
``` 
And Check shape of output array like this 
It should be "(batch, 56, 8400)"
```
            # 　(batch, 56, 8400)　＞(batch, 8400, 56) for yolov8
            print(f'out.shape : {out.shape}') 
            out = out.transpose((0, 2, 1))
```

Also check  scalar in `def map_to_zero_one`  too
```
def map_to_zero_one(scalar):
    print('[map_to_zero_one]  scalar\n   {scalar}')
    print('[map_to_zero_one]  scalar.shape :  {scalar.shape}')
    scalar_min = np.min(scalar)
    scalar_max = np.max(scalar)
    mapped = (scalar - scalar_min) / (scalar_max - scalar_min)
    return mapped
```

**Comment by minjea1588** [comment]
I deleted custom_lib in dstest_yolo_nopostprocess_v8_pose_triton.txt, but the same problem still appears.
The shape before transposing is (1, 56, 8400). 
[map_to_zero_one] scalar.shape: (1, 8400, 4). 
But still the same problem is appearing.

![image](https://github.com/YunghuiHsu/deepstream-yolo-pose/assets/104705868/70e51cf9-d106-4591-88db-c4d5a7320110)

**Comment by YunghuiHsu** [comment]
your shape of output and scalar seems correct.

The error message "overflow encountered in subtract" indicates that the operation `scalar − scalar_min` is causing an overflow, likely because the values in scalar or scalar_min are too large or too small to fit within the data type.

- Check Data Types: Ensure that the data type of scalar can handle the range of values you're dealing with. If you're using NumPy arrays, you can check the data type with scalar.dtype.

- Check Values: Print or log the minimum and maximum values within scalar. This will help you understand if there are any extremely large or small values that could be causing the overflow.

```
import numpy as np

def map_to_zero_one(scalar):
    print(f'[map_to_zero_one]  scalar.shape :  {scalar.shape}')
    print(f'[map_to_zero_one]  scalar.dtype :  {scalar.dtype}')
    
    scalar_min = np.min(scalar)
    scalar_max = np.max(scalar)
    
    print(f'[map_to_zero_one]  scalar_min :  {scalar_min}')
    print(f'[map_to_zero_one]  scalar_max :  {scalar_max}')
    
    
    mapped = (scalar - scalar_min) / (scalar_max - scalar_min)
    return mapped

```

**Comment by minjea1588** [comment]
![image](https://github.com/YunghuiHsu/deepstream-yolo-pose/assets/104705868/5f9dce40-656c-4192-93f2-d1b428ead888)
It seems that the problem occurs because nan is entered in the scalar value.

**Comment by YunghuiHsu** [comment]
`out[..., :4]`  means coordinates of bounding box.

I didn't encounter this problem when I used NVInfer instead of NVInferserver.

Try  use `np.nanmin` 、`np.nanmax` replace  `np.min`、`np.max`  in `def map_to_zero_one(scalar)`

This may solve the problems encountered during the normalization stage of the bbox coordinates, but the underlying reason is that the bbox coordinates should not theoretically have NaN, and perhaps other problems will be encountered in the post-processing stage.

**Comment by minjea1588** [comment]
thank you for the reply. It seems that nvinfer, external tritonserver, and deepstreamtriton all have different data structures. I'll have to find another way to preprocess it.

**Comment by YunghuiHsu** [comment]
Good luck in finding a solution.Please let me know if you figure out the correct way to set up NVInferserver, if it's convenient for you, thank you!

**Comment by minjea1588** [comment]
It's been a while. I found it. When infernece with triton, the network_info.width and network_info.height values ​​are 0,0. If change this part to 640 640, it will work!
![image](https://github.com/YunghuiHsu/deepstream-yolo-pose/assets/104705868/07e42936-9bf2-4713-8d4c-d619b0d75ace)

**Comment by YunghuiHsu** [comment]
> It's been a while. I found it. When infernece with triton, the network_info.width and network_info.height values ​​are 0,0. If change this part to 640 640, it will work! ![image](https://user-images.githubusercontent.com/104705868/267258373-07e42936-9bf2-4713-8d4c-d619b0d75ace.png)

That's great. Congratulations.

I'm keeping this code specifically for debugging information and dynamic scaling.

**Comment by minjea1588** [comment]
![image](https://github.com/YunghuiHsu/deepstream-yolo-pose/assets/104705868/d49457b9-55a8-4f3e-8b56-df63af74b57b)


There is one more thing: when a 640x640 model is displayed on the screen at 1920x1080, it is displayed as such. 640x640 works fine. What processing should be done when operating at 1920x1080?

**Comment by YunghuiHsu** [comment]
Because the model is inferred to be 640x640, it has to be scaled to the size you want to display

Here is display and rescale related code:
You might consider setting input_shape to a constant.
```python=!
MUXER_OUTPUT_WIDTH = 640  # stream input
MUXER_OUTPUT_HEIGHT = 360  # stream input
TILED_OUTPUT_WIDTH = 1280 # stream output
TILED_OUTPUT_HEIGHT = 720 # stream output

def pose_src_pad_buffer_probe(pad, info, u_data):
                ...
                network_info = tensor_meta.network_info
                input_shape = (network_info.width, network_info.height)
                ...
                out[..., [0, 2]] = out[..., [0, 2]] * network_info.width  # scale to screen width
                out[..., [1, 3]] = out[..., [1, 3]] * network_info.height  # scale to screen height
